### ISSUE TITLE
Cleanup TODOs -> Issues

### ISSUE THREAD

**Issue by cleong110** [sign-language-processing/sign-language-processing.github.io#67]
index.md has a number of TODOs which have either been done, or documented as issues. For example 

```

<!-- TODO: gloss translation (Mathias) -->
<!-- @article{muller2022considerations,
  title={Considerations for meaningful sign language machine translation based on glosses},
  author={M{\"u}ller, Mathias and Jiang, Zifan and Moryossef, Amit and Rios, Annette and Ebling, Sarah},
  journal={arXiv preprint arXiv:2211.15464},
  year={2022}
} -->
```

- [x] RWTH-PHOENIX-WEATHER (the 2015 continuous SLR set, koller2015ContinuousSLR, not the translation set!) to list of datasets #70
- [x] FHAD dataset (https://guiggh.github.io/publications/first-person-hands/) #94
- [x] SLR500 to list of datasets huang2019attention3DCNNsSLR https://ieeexplore.ieee.org/document/8466903 #73 
- [x] [this thesis](https://scholarsarchive.byu.edu/cgi/viewcontent.cgi?article=6477&context=etd) page 26 has more datasets. #68 
- [x] BLEURT explanation, used in Rust et al 2024 #95 
- [x] DailyMoth dataset, from Rust et al 2024. Table 8 has stats: 497 videos, 70 hours, 1 signer, vocabulary of words 19 740, segmented video clips #93
- [x] AFRISIGN dataset #75 
- [x] VGT Corpus (dataset:herreweghe2015VGTCorpus) #74 
- [x] CiCo #56 
- [x] BSL-1K dataset, cited in Cheng2023CiCoSignLanguageRetrieval. https://github.com/gulvarol/bsl1k #71

**Comment by cleong110** [comment]
Done!
